### ISSUE TITLE
FYI: parallelly::supportsMulticore()

### ISSUE THREAD

**Issue by HenrikBengtsson** [cran/fiery#1]
FYI, instead of:

```r
can_fork <- NULL
#' @importFrom parallelly availableCores
on_load({can_fork <- availableCores("multicore") > 1L})
```

you could use `parallelly::supportsMulticore()`.  Other than be more clear, the advantage would be to that it returns TRUE also when there's a single core available.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by HenrikBengtsson** [comment]
Doh.  Moved to <https://github.com/thomasp85/fiery/issues/52>.
